blank_issues_enabled: false
contact_links:
  - name: Renewed Scripts
    url: https://discord.gg/PtA9rvvR7T
    about: Ask questions, receive support, and discuss with the community in our Discord server.
