RegisterNUICallback("OnHideSettingsMenu", function(_, cb)
    SetNuiFocus(false, false)
    cb(true)
end)

RegisterNUICallback("OnGearModeChanged", function(newMode, cb)
    Wait(500)
    Koci.Client.HUD:ChangeGearMode(newMode)
    cb(true)
end)

RegisterNUICallback("loadLocaleFile", function(_, cb)
    Wait(1)
    Koci.Client:SendReactMessage("setLocale", locales.ui)
    cb(true)
end)

RegisterNUICallback("OnSettingsSaved", function(_, cb)
    Koci.Client:SendNotify(_t("hud.settings.saved"))
    cb(true)
end)

RegisterNUICallback("OnVehicleHudChanged", function(data, cb)
    Koci.Client.HUD:UpdateVehicleHud(data.newVH)
    cb(true)
end)

RegisterNUICallback("openBigMap", function(_, cb)
    SetNuiFocus(false, false)
    ActivateFrontendMenu(GetHashKey("FE_MENU_VERSION_MP_PAUSE"), 0, -1)
    cb(true)
end)

RegisterNUICallback("openPauseMenu", function(_, cb)
    SetNuiFocus(false, false)
    ActivateFrontendMenu(GetHashKey("FE_MENU_VERSION_LANDING_MENU"), 0, -1)
    cb(true)
end)
