fx_version "adamant"
game "gta5"

files {
	'audioconfig/*.dat151.rel',
	'audioconfig/*.dat54.rel',
	'sfx/**/*.awc',
	'sfx/**/*.awc',
  }
  data_file "AUDIO_GAMEDATA" "audioconfig/lg228nathemi64_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg228nathemi64_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg228nathemi64"
  data_file "AUDIO_GAMEDATA" "audioconfig/lg227hemi64_game.dat"
  data_file "AUDIO_SOUNDDATA" "audioconfig/lg227hemi64_sounds.dat"
  data_file "AUDIO_WAVEPACK" "sfx/dlc_lg227hemi64"
  data_file "AUDIO_GAMEDATA" "audioconfig/lg221srt8hemi_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg221srt8hemi_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg221srt8hemi"
data_file "AUDIO_SYNTHDATA" "audioconfig/kc107hemipwagon4inch_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/kc107hemipwagon4inch_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/kc107hemipwagon4inch_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_kc107hemipwagon4inch"
data_file "AUDIO_SYNTHDATA" "audioconfig/lgcy01chargerv8_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lgcy01chargerv8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lgcy01chargerv8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lgcy01chargerv8"
data_file "AUDIO_GAMEDATA" "audioconfig/lg228nathemi64_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg228nathemi64_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg228nathemi64"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/demonv8_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/demonv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/demonv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_demonv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/diablov12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/diablov12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_diablov12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta017nismorb_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta017nismorb_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta017nismorb'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg98tahoepol_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg98tahoepol_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg98tahoepol_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg98tahoepol"
data_file 'AUDIO_GAMEDATA' 'audioconfig/tagt3flat6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tagt3flat6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tagt3flat6'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta028viper_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta028viper_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta028viper'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq46forgtebv6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq46forgtebv6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq46forgtebv6'
data_file "AUDIO_SYNTHDATA" "audioconfig/ml720v8eng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/ml720v8eng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/ml720v8eng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_ml720v8eng"
data_file "AUDIO_GAMEDATA" "audioconfig/kc118ls3camst2sc_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/kc118ls3camst2sc_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_kc118ls3camst2sc"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg67koagerars_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg67koagerars_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg67koagerars_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg67koagerars"
data_file 'AUDIO_GAMEDATA' 'audioconfig/fordvoodoo_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/fordvoodoo_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_fordvoodoo'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg41ttviperv10_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg41ttviperv10_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg41ttviperv10_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg41ttviperv10"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg14c6vette_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg14c6vette_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg14c6vette_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg14c6vette"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/lg100rptorv8_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lg100rptorv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lg100rptorv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lg100rptorv8'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg14c6vettena_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg14c6vettena_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg14c6vettena_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg14c6vettena"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg42naviperv10_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg42naviperv10_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg42naviperv10_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg42naviperv10"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg52musgt500v8_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg52musgt500v8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg52musgt500v8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg52musgt500v8"
data_file "AUDIO_SYNTHDATA" "audioconfig/mbnzc63eng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/mbnzc63eng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/mbnzc63eng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_mbnzc63eng"
data_file 'AUDIO_GAMEDATA' 'audioconfig/predatorv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/predatorv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_predatorv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta183lt1_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta183lt1_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta183lt1'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tagt3flat6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tagt3flat6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tagt3flat6'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tamustanggt50_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tamustanggt50_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tamustanggt50'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tascmustanggt50_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tascmustanggt50_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tascmustanggt50'
data_file "AUDIO_GAMEDATA" "audioconfig/350zsound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/350zsound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_350zsound"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/nisgtr35_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/nisgtr35_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/nisgtr35_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_nisgtr35'
data_file "AUDIO_SYNTHDATA" "audioconfig/rx7bpeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/rx7bpeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/rx7bpeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_rx7bpeng"
data_file 'AUDIO_GAMEDATA' 'audioconfig/r35sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/r35sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_r35sound'
data_file "AUDIO_GAMEDATA" "audioconfig/aq10nisvr38dett_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq10nisvr38dett_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq10nisvr38dett"
data_file "AUDIO_GAMEDATA" "audioconfig/aq42chedrag427_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/aq42chedrag427_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_aq42chedrag427"
data_file "AUDIO_GAMEDATA" "audioconfig/bgw16_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/bgw16_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_bgw16"
data_file "AUDIO_GAMEDATA" "audioconfig/chevroletlt4_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/chevroletlt4_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_chevroletlt4"
data_file "AUDIO_GAMEDATA" "audioconfig/harleysound_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/harleysound_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_harleysound"
data_file "AUDIO_GAMEDATA" "audioconfig/kc63fordgt2gen_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/kc63fordgt2gen_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_kc63fordgt2gen"
data_file "AUDIO_GAMEDATA" "audioconfig/lg44nascarv8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg44nascarv8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg44nascarv8"
data_file "AUDIO_GAMEDATA" "audioconfig/lg57mustangtv8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg57mustangtv8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg57mustangtv8"
data_file "AUDIO_GAMEDATA" "audioconfig/lg62chironpursport_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg62chironpursport_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg62chironpursport"
data_file "AUDIO_GAMEDATA" "audioconfig/lg67koagerars_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg67koagerars_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg67koagerars"
data_file "AUDIO_GAMEDATA" "audioconfig/lg81hcredeye_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg81hcredeye_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg81hcredeye"
data_file "AUDIO_GAMEDATA" "audioconfig/s54b32_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/s54b32_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_s54b32"
data_file "AUDIO_GAMEDATA" "audioconfig/s63b44_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/s63b44_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_s63b44"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/2strkbeng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/2strkbeng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/2strkbeng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_2strkbeng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq02coyotef150_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq02coyotef150_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq02coyotef150'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq42chedrag427_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq42chedrag427_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq42chedrag427'
data_file 'AUDIO_GAMEDATA' 'audioconfig/audiwx_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/audiwx_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_audiwx'
data_file 'AUDIO_GAMEDATA' 'audioconfig/audi7a_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/audi7a_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_audi7a'
data_file 'AUDIO_GAMEDATA' 'audioconfig/audiea855_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/audiea855_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_audiea855'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cammedcharger_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cammedcharger_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cammedcharger'
data_file "AUDIO_SYNTHDATA" "audioconfig/chevydmaxeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/chevydmaxeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/chevydmaxeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_chevydmaxeng"
data_file 'AUDIO_GAMEDATA' 'audioconfig/harleysound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/harleysound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_harleysound'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg69patrolcharger_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg69patrolcharger_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg69patrolcharger_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg69patrolcharger"
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq07powerstroke67_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq07powerstroke67_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq07powerstroke67'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq07powerstroke67_npc'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s63b44_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s63b44_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s63b44'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tacumminsb_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tacumminsb_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tacumminsb'
data_file 'AUDIO_GAMEDATA' 'audioconfig/genx_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/genx_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_genx'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trent1000_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trent1000_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_trent1000'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trent1000tss_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trent1000tss_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_trent1000tss'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cfm562c5_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cfm562c5_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cfm562c5'
data_file 'AUDIO_GAMEDATA' 'audioconfig/jt3d3b_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/jt3d3b_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_jt3d3b'
data_file 'AUDIO_GAMEDATA' 'audioconfig/jt3d7_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/jt3d7_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_jt3d7'
data_file 'AUDIO_GAMEDATA' 'audioconfig/jt3c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/jt3c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_jt3c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cfm565_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cfm565_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cfm565'
data_file 'AUDIO_GAMEDATA' 'audioconfig/iaev2500_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/iaev2500_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_iaev2500'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cfmleap1a_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cfmleap1a_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cfmleap1a'
data_file 'AUDIO_GAMEDATA' 'audioconfig/pw1100g_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/pw1100g_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_pw1100g'
data_file 'AUDIO_GAMEDATA' 'audioconfig/jt8d_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/jt8d_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_jt8d'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cfm563b_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cfm563b_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cfm563b'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cfm567b_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cfm567b_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cfm567b'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cfmleap1b_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cfmleap1b_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cfmleap1b'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/pt6a67d_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/pt6a67d_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/pt6a67d_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_pt6a67d'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/ct79b_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ct79b_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ct79b_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ct79b'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/pw150a_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/pw150a_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/pw150a_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_pw150a'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/pw127m_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/pw127m_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/pw127m_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_pw127m'
data_file 'AUDIO_GAMEDATA' 'audioconfig/io540_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/io540_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_io540'
data_file 'AUDIO_GAMEDATA' 'audioconfig/io360_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/io360_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_io360'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lf507_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lf507_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lf507'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trent500_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trent500_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_trent500'
data_file 'AUDIO_GAMEDATA' 'audioconfig/pw2000_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/pw2000_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_pw2000'
data_file 'AUDIO_GAMEDATA' 'audioconfig/rb211535_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rb211535_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rb211535'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cf650c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cf650c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cf650c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cf650e_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cf650e_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cf650e'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cf680c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cf680c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cf680c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trentxwb97_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trentxwb97_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_trentxwb97'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tf34ge100a_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tf34ge100a_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tf34ge100a'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/pw200_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/pw200_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/pw200_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_pw200'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/ge400_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ge400_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ge400_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ge400'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/f119pw100_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f119pw100_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f119pw100_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f119pw100'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/f404_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f404_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f404_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f404'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/olympus593_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/olympus593_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/olympus593_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_olympus593'
data_file 'AUDIO_GAMEDATA' 'audioconfig/genx2b_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/genx2b_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_genx2b'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ge90115b_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ge90115b_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ge90115b'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sentinelsg4_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sentinelsg4_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_sentinelsg4'
data_file 'AUDIO_GAMEDATA' 'audioconfig/argento_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/argento_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_argento'
data_file 'AUDIO_GAMEDATA' 'audioconfig/elegyx_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/elegyx_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_elegyx'
data_file 'AUDIO_GAMEDATA' 'audioconfig/majimalm_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/majimalm_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_majimagt'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/monroec_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/monroec_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/monroec_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_monroec'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trumpetzrc_game.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/trumpetzr_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trumpetzrc_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/trumpetzr_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_trumpetzr'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ariant_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ariant_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ariant'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cw2019_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cw2019_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cw2019'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sultanrsv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sultanrsv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_v8sultanrs'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/stratumc_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/stratumc_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/stratumc_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_zircoflow'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/gresleyh_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/gresleyh_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gresleyh_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gresleyh'
data_file 'AUDIO_GAMEDATA' 'audioconfig/skart_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/skart_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_skart'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lfasound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lfasound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lfasound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/r34sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/r34sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_r34sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/hemisound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/hemisound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_hemisound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s15sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s15sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s15sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aventadorv12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aventadorv12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aventadorv12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/svjsound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/svjsound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_svjsound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ftypesound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ftypesound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ftypesound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lambov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lambov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lambov10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f10m5_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f10m5_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f10m5'
data_file 'AUDIO_GAMEDATA' 'audioconfig/rb26dett_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rb26dett_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rb26dett'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s85b50_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s85b50_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s85b50'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f20c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f20c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f20c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/npolchar_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/npolchar_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_npolchar'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ecoboostv6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ecoboostv6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ecoboostv6'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cvpiv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cvpiv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cvpiv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/subaruej20_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/subaruej20_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_subaruej20'
data_file 'AUDIO_GAMEDATA' 'audioconfig/fordvoodoo_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/fordvoodoo_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_fordvoodoo'
data_file 'AUDIO_GAMEDATA' 'audioconfig/n4g63t_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/n4g63t_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_n4g63t'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta488f154_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta488f154_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta488f154'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s85b50_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s85b50_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s85b50'
data_file 'AUDIO_GAMEDATA' 'audioconfig/npolchar_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/npolchar_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_npolchar'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ecoboostv6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ecoboostv6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ecoboostv6'
data_file 'AUDIO_GAMEDATA' 'audioconfig/porsche57v10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/porsche57v10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_porsche57v10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cvpiv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cvpiv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cvpiv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/rb26dett_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rb26dett_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rb26dett'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f20c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f20c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f20c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lambov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lambov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lambov10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ea825_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ea825_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ea825'
data_file 'AUDIO_GAMEDATA' 'audioconfig/rotary7_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rotary7_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rotary7'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq35ferf154cd_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq35ferf154cd_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq35ferf154cd'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq02coyotef150_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq02coyotef150_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq02coyotef150'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq26mit4b11t_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq26mit4b11t_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq26mit4b11t'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cummins5924v_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cummins5924v_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cummins5924v'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq22honb18c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq22honb18c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq22honb18c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq14nisvq37vhrt_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq14nisvq37vhrt_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq14nisvq37vhrt'
data_file 'AUDIO_GAMEDATA' 'audioconfig/m158huayra_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m158huayra_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m158huayra'
data_file 'AUDIO_GAMEDATA' 'audioconfig/rb28dett_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rb28dett_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rb28dett'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq10nisvr38dett_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq10nisvr38dett_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq10nisvr38dett'
data_file 'AUDIO_GAMEDATA' 'audioconfig/m297zonda_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m297zonda_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m297zonda'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq03ej257_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq03ej257_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq03ej257'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq05ej257el_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq05ej257el_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq05ej257el'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq2jzgterace_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq2jzgterace_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq2jzgterace'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aqtoy2jzstock_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqtoy2jzstock_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqtoy2jzstock'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aqls7raceswap_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqls7raceswap_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqls7raceswap'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aqm275amg_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqm275amg_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqm275amg'
data_file 'AUDIO_GAMEDATA' 'audioconfig/k20a_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/k20a_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_k20a'
data_file 'AUDIO_GAMEDATA' 'audioconfig/k20c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/k20c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_k20c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aston59v12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aston59v12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aston59v12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/alfa690t_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/alfa690t_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_alfa690t'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s65b40_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s65b40_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s65b40'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ea888_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ea888_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ea888'
data_file 'AUDIO_GAMEDATA' 'audioconfig/b58b30_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/b58b30_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_b58b30'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s54b32_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s54b32_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s54b32'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mercm177_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mercm177_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mercm177'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s63b44_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s63b44_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s63b44'
data_file 'AUDIO_GAMEDATA' 'audioconfig/porschema2_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/porschema2_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_porschema2'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg52musgt500v8_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg52musgt500v8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg52musgt500v8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg52musgt500v8"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg44nascarv8_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg44nascarv8_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg44nascarv8_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg44nascarv8"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/bgw16_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/bgw16_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/bgw16_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_bgw16'
data_file "AUDIO_SYNTHDATA" "audioconfig/srtvipeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/srtvipeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/srtvipeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_srtvipeng"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/nisgtr35_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/nisgtr35_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/nisgtr35_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_nisgtr35'
data_file "AUDIO_SYNTHDATA" "audioconfig/gt3rstun_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/gt3rstun_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/gt3rstun_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_gt3rstun"
data_file 'AUDIO_GAMEDATA' 'audioconfig/53vortec_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/53vortec_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_53vortec'
data_file 'AUDIO_GAMEDATA' 'audioconfig/64powerstroke_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/64powerstroke_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_64powerstroke'
data_file 'AUDIO_GAMEDATA' 'audioconfig/46fordmodular_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/46fordmodular_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_46fordmodular'
data_file 'AUDIO_GAMEDATA' 'audioconfig/12vcummins_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/12vcummins_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_12vcummins'
data_file "AUDIO_SYNTHDATA" "audioconfig/audr8tteng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/audr8tteng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/audr8tteng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_audr8tteng"

client_script {
    'vehicle_names.lua'
}