Language = {
    ['buy_mining'] = 'Buy Mining Stuff',
    ['sell_stuff'] = 'Sell Stuff',
    ['plant_c4'] = 'Press ~INPUT_CONTEXT~ to mine',
    ['no_c4'] = 'You Need C4',
    ['stay_away'] = 'Stay Away from the C4',
    ['get_emereld'] = 'Crack Emereld',
    ['drill_stone'] = 'Drill Stone',
    ['no_drill'] = 'You Need Drill to Break the Stone',
    ['mining_shop'] = 'Mining Shop',
    ['sell_mining'] = 'Sell Mined Stuff',
    ['select_item'] = 'Select Item',
    ['nodrill_hammer'] = 'You Need Drill and Hammer to Break the Stone',
    ['doing_something'] = 'you are already doing something',
    ['brake_stone'] = 'Crack Stone',
    ['shape_item'] = 'Create good shape of items',
    ['start_working'] = 'Start Working',
    ['prog_shapemetal'] = 'Shaping Ore',
    ['prog_meltmetal'] = 'Melting Metals',
    ['prog_pourmetal'] = 'Pouring Metals',
    ['prog_washmetal'] = 'Washing Metals',
    ['not_enough'] = "you don't have enough items",
    ['melt_metal'] = "Melt your metals here",
    ['start_melting'] = "Start Melting",
    ['melt_first'] = "you need to melt metal first",
    ['mined'] = "You Mined one ",
    ['no_metal'] = "You don't have any metals",
    ['metal_washed'] = "You washed your all metals",
    ['you_got'] = "You got ",
    ['sell'] = "Sell",
    ['amount'] = "Amount",


}