function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry("tr_emsambo_callsign_a0", "[TR] Callsign A")
    AddTextEntry("tr_emsambo_callsign_a1", "[TR] Callsign B")
    AddTextEntry("tr_emsambo_callsign_a2", "[TR] Callsign C")
    AddTextEntry("tr_emsambo_callsign_a3", "[TR] Callsign D")
    AddTextEntry("tr_emsambo_callsign_a4", "[TR] Callsign E")
    AddTextEntry("tr_emsambo_callsign_a5", "[TR] Callsign F")
    AddTextEntry("tr_emsambo_callsign_a6", "[TR] Callsign G")
    AddTextEntry("tr_emsambo_callsign_a7", "[TR] Callsign H")
    AddTextEntry("tr_emsambo_callsign_a8", "[TR] Callsign I")
    AddTextEntry("tr_emsambo_callsign_a9", "[TR] Callsign J")
    AddTextEntry("tr_emsambo_callsign_a10", "[TR] Callsign K")
    AddTextEntry("tr_emsambo_callsign_a11", "[TR] Callsign L")
    AddTextEntry("tr_emsambo_callsign_a12", "[TR] Callsign M")
    AddTextEntry("tr_emsambo_callsign_a13", "[TR] Callsign N")
    AddTextEntry("tr_emsambo_callsign_a14", "[TR] Callsign O")
    AddTextEntry("tr_emsambo_callsign_a15", "[TR] Callsign P")
    AddTextEntry("tr_emsambo_callsign_a16", "[TR] Callsign Q")
    AddTextEntry("tr_emsambo_callsign_a17", "[TR] Callsign R")
    AddTextEntry("tr_emsambo_callsign_a18", "[TR] Callsign S")
    AddTextEntry("tr_emsambo_callsign_a19", "[TR] Callsign T")
    AddTextEntry("tr_emsambo_callsign_a20", "[TR] Callsign U")
    AddTextEntry("tr_emsambo_callsign_a21", "[TR] Callsign V")
    AddTextEntry("tr_emsambo_callsign_a22", "[TR] Callsign W")
    AddTextEntry("tr_emsambo_callsign_a23", "[TR] Callsign X")
    AddTextEntry("tr_emsambo_callsign_a24", "[TR] Callsign Y")
    AddTextEntry("tr_emsambo_callsign_a25", "[TR] Callsign Z")
    AddTextEntry("tr_emsambo_callsign_b0", "[TR] CallSign 0")
    AddTextEntry("tr_emsambo_callsign_b1", "[TR] CallSign 1")
    AddTextEntry("tr_emsambo_callsign_b2", "[TR] CallSign 2")
    AddTextEntry("tr_emsambo_callsign_b3", "[TR] CallSign 3")
    AddTextEntry("tr_emsambo_callsign_b4", "[TR] CallSign 4")
    AddTextEntry("tr_emsambo_callsign_b5", "[TR] CallSign 5")
    AddTextEntry("tr_emsambo_callsign_b6", "[TR] CallSign 6")
    AddTextEntry("tr_emsambo_callsign_b7", "[TR] CallSign 7")
    AddTextEntry("tr_emsambo_callsign_b8", "[TR] CallSign 8")
    AddTextEntry("tr_emsambo_callsign_b9", "[TR] CallSign 9")
    AddTextEntry("tr_emsambo_callsign_c0", "[TR] CallSign 0")
    AddTextEntry("tr_emsambo_callsign_c1", "[TR] CallSign 1")
    AddTextEntry("tr_emsambo_callsign_c2", "[TR] CallSign 2")
    AddTextEntry("tr_emsambo_callsign_c3", "[TR] CallSign 3")
    AddTextEntry("tr_emsambo_callsign_c4", "[TR] CallSign 4")
    AddTextEntry("tr_emsambo_callsign_c5", "[TR] CallSign 5")
    AddTextEntry("tr_emsambo_callsign_c6", "[TR] CallSign 6")
    AddTextEntry("tr_emsambo_callsign_c7", "[TR] CallSign 7")
    AddTextEntry("tr_emsambo_callsign_c8", "[TR] CallSign 8")
    AddTextEntry("tr_emsambo_callsign_c9", "[TR] CallSign 9")
    AddTextEntry("tr_emsambo_callsign_d0", "[TR] CallSign 0")
    AddTextEntry("tr_emsambo_callsign_d1", "[TR] CallSign 1")
    AddTextEntry("tr_emsambo_callsign_d2", "[TR] CallSign 2")
    AddTextEntry("tr_emsambo_callsign_d3", "[TR] CallSign 3")
    AddTextEntry("tr_emsambo_callsign_d4", "[TR] CallSign 4")
    AddTextEntry("tr_emsambo_callsign_d5", "[TR] CallSign 5")
    AddTextEntry("tr_emsambo_callsign_d6", "[TR] CallSign 6")
    AddTextEntry("tr_emsambo_callsign_d7", "[TR] CallSign 7")
    AddTextEntry("tr_emsambo_callsign_d8", "[TR] CallSign 8")
    AddTextEntry("tr_emsambo_callsign_d9", "[TR] CallSign 9")
    AddTextEntry("tr_emsambo_callsign_e0", "[TR] CallSign 0")
    AddTextEntry("tr_emsambo_callsign_e1", "[TR] CallSign 1")
    AddTextEntry("tr_emsambo_callsign_e2", "[TR] CallSign 2")
    AddTextEntry("tr_emsambo_callsign_e3", "[TR] CallSign 3")
    AddTextEntry("tr_emsambo_callsign_e4", "[TR] CallSign 4")
    AddTextEntry("tr_emsambo_callsign_e5", "[TR] CallSign 5")
    AddTextEntry("tr_emsambo_callsign_e6", "[TR] CallSign 6")
    AddTextEntry("tr_emsambo_callsign_e7", "[TR] CallSign 7")
    AddTextEntry("tr_emsambo_callsign_e8", "[TR] CallSign 8")
    AddTextEntry("tr_emsambo_callsign_e9", "[TR] CallSign 9")
    AddTextEntry("tr_emsambo_livery1", "[TR] EMS Livery 1")
    AddTextEntry("tr_emsambo_livery2", "[TR] EMS Livery 2")
    AddTextEntry("tr_emsambo_ant_1a", "[TR] state Range")
    AddTextEntry("tr_emsambo_rwnull_1a", "[TR] Black/Red Window Decal")
    AddTextEntry("tr_emsambo_rwnull_1b", "[TR] Blue Window Decal")
    AddTextEntry("tr_emsambo_rwnull_1c", "[TR] Red Window Decal")
    AddTextEntry("tr_emsambo_box_1a", "[TR] Ambulance Decal")
    AddTextEntry("tr_emsambo_windowdecal_1a", "[TR] Paramedic")
    AddTextEntry("tr_emsambo_windowdecal_2a", "[TR] Med. Service")
    AddTextEntry("tr_emsambo_nwnull_1a", "[TR] First / Last Name")
end)
