--[[ 
░██████╗██╗░░░██╗███╗░░██╗░██████╗░█████╗░██████╗░██╗██████╗░████████╗░██████╗
██╔════╝╚██╗░██╔╝████╗░██║██╔════╝██╔══██╗██╔══██╗██║██╔══██╗╚══██╔══╝██╔════╝
╚█████╗░░╚████╔╝░██╔██╗██║╚█████╗░██║░░╚═╝██████╔╝██║██████╔╝░░░██║░░░╚█████╗░
░╚═══██╗░░╚██╔╝░░██║╚████║░╚═══██╗██║░░██╗██╔══██╗██║██╔═══╝░░░░██║░░░░╚═══██╗
██████╔╝░░░██║░░░██║░╚███║██████╔╝╚█████╔╝██║░░██║██║██║░░░░░░░░██║░░░██████╔╝
╚═════╝░░░░╚═╝░░░╚═╝░░╚══╝╚═════╝░░╚════╝░╚═╝░░╚═╝╚═╝╚═╝░░░░░░░░╚═╝░░░╚═════╝░

https://discord.gg/ZbmaduFFqv 




    --░░░░░░░░░░░░███████╗██████╗░██╗████████╗░░░░░░░░░░░░
    --░░░░░░░░░░░░██╔════╝██╔══██╗██║╚══██╔══╝░░░░░░░░░░░░
    --█████╗█████╗█████╗░░██║░░██║██║░░░██║░░░█████╗█████╗
    --╚════╝╚════╝██╔══╝░░██║░░██║██║░░░██║░░░╚════╝╚════╝
    --░░░░░░░░░░░░███████╗██████╔╝██║░░░██║░░░░░░░░░░░░░░░
    --░░░░░░░░░░░░╚══════╝╚═════╝░╚═╝░░░╚═╝░░░░░░░░░░░░░░░
    --EDIT: 
-- By Searching the phrase "--EDIT:" you can quickly move bewteen the most common customization locations in this config. 
]]
Config = {
    Framework = "QB", -- "ESX" or "QB" EDIT in edit.lua
    Debug = true,
    
    AutoReporting =true, -- Use auto reporting to generate reports of crimes^ check edit.lua for customizations.
    PoliceJob = "police",
    FireDeptJob = "ambulance",
    AmbulanceJob = "ambulance",


    DispatcherToggleKey = 'F9', --Key to turn off the audio for 
    
    GenericReportingChance = {60,40}, -- {Day,Night} Reporting chance for auto generated alerts
    IgnoredAreas = {coords = vector3(0,0,0), distance = 1}, -- Areas to ignore and the distance from the triggered coords they are ignored to
    ServerSidedAlertSpamRestrictionDistance = 100, -- in GTA units similar to meters
    ServerSidedAlertSpamRestrictionDuration = 120, -- in seconds higher wait means less spam incoming

    PlateReadingChance = 10,
    SuspectRaceGenderReportingChance = 50,-- only when not masked
    SuspectAppearanceHairColorReportingChance = 60,
    SuspectAppearanceTattooReportingChance = -1, --Not Yet Added: Do not change
    SuspectAppearanceScarringReportingChance = -1, --Not Yet Added: Do not change
   
   
    VehicleSpeedReportingChance = 40,
    VehicleColorReportingChance = 60,
    VehicleArmedPlayerReportingChance = 2,

    SpeedLimitExceededPercentForSpeeding = 0.3, -- (0.2 = 20 percent of over or if speedlimit is 60mph speeding is 72mph or over) the percentage expressed as a decimal that you exceed the speed limit of a street to trigger speeding.
    VehicleSideWalkeSPeedForDangerousDriver = 60.0 , -- the speed you must exceed on a sidewalk to be a dangerous driver
    VehicleParkingVilationSpeed = 10.0,
    IllegalParkingTimeViolation = 10, -- time in seconds until an illegally parked vehicle gets reported. This is a novely would recommend keeping chances low as it requires a loop to check. 
    
    SpeedLimits = {
        ["Grapeseed Main St"] = 35.0,
        ["Grapeseed Ave"] = 35.0,
        ["Joad Ln"] = 35.0,
        ["Union Rd"] = 40.0,
        ["O'Neil Way"] = 25.0,
        ["Senora Fwy"] = 65.0,
        ["Catfish View"] = 35.0,
        ["Great Ocean Hwy"] = 65.0,
        ["Paleto Blvd"] = 35.0,
        ["Duluoz Ave"] = 35.0,
        ["Procopio Dr"] = 35.0,
        ["Cascabel Ave"] = 30.0,
        ["Procopio Promenade"] = 25.0,
        ["Pyrite Ave"] = 30.0,
        ["Fort Zancudo Approach Rd"] = 25.0,
        ["Barbareno Rd"] = 30.0,
        ["Ineseno Road"] = 30.0,
        ["West Eclipse Blvd"] = 35.0,
        ["East Joshua Road"] = 50.0,
        ["Marina Dr"] = 35.0,
        ["Alhambra Dr"] = 35.0,
        ["Niland Ave"] = 35.0,
        ["Zancudo Ave"] = 35.0,
        ["Armadillo Ave"] = 35.0,
        ["Algonquin Blvd"] = 35.0,
        ["Mountain View Dr"] = 35.0,
        ["Cholla Springs Ave"] = 35.0,
        ["Panorama Dr"] = 40.0,
        ["Lesbos Ln"] = 35.0,
        ["Calafia Rd"] = 30.0,
        ["North Calafia Way"] = 30.0,
        ["Cassidy Trail"] = 25.0,
        ["Seaview Rd"] = 35.0,
        ["Playa Vista"] = 30.0,
        ["Bay City Ave"] = 30.0,
        ["Del Perro Fwy"] = 65.0,
        ["Equality Way"] = 30.0,
        ["Red Desert Ave"] = 30.0,
        ["Magellan Ave"] = 25.0,
        ["Sandcastle Way"] = 30.0,
        ["Vespucci Blvd"] = 40.0,
        ["Prosperity St"] = 30.0,
        ["San Andreas Ave"] = 40.0,
        ["North Rockford Dr"] = 35.0,
        ["South Rockford Dr"] = 35.0,
        ["Marathon Ave"] = 30.0,
        ["Boulevard Del Perro"] = 35.0,
        ["Cougar Ave"] = 30.0,
        ["Liberty St"] = 30.0,
        ["Bay City Incline"] = 40.0,
        ["Conquistador St"] = 25.0,
        ["Cortes St"] = 25.0,
        ["Vitus St"] = 25.0,
        ["Aguja St"] = 25.0,
        ["Goma St"] = 25.0,
        ["Melanoma St"] = 25.0,
        ["Palomino Ave"] = 35.0,
        ["Invention Ct"] = 25.0,
        ["Imagination Ct"] = 25.0,
        ["Rub St"] = 25.0,
        ["Tug St"] = 25.0,
        ["Ginger St"] = 30.0,
        ["Lindsay Circus"] = 30.0,
        ["Calais Ave"] = 35.0,
        ["Adam's Apple Blvd"] = 40.0,
        ["Alta St"] = 40.0,
        ["Integrity Way"] = 30.0,
        ["Swiss St"] = 30.0,
        ["Strawberry Ave"] = 40.0,
        ["Capital Blvd"] = 30.0,
        ["Crusade Rd"] = 30.0,
        ["Innocence Blvd"] = 40.0,
        ["Davis Ave"] = 40.0,
        ["Little Bighorn Ave"] = 35.0,
        ["Roy Lowenstein Blvd"] = 35.0,
        ["Jamestown St"] = 30.0,
        ["Carson Ave"] = 35.0,
        ["Grove St"] = 30.0,
        ["Brouge Ave"] = 30.0,
        ["Covenant Ave"] = 30.0,
        ["Dutch London St"] = 40.0,
        ["Signal St"] = 30.0,
        ["Elysian Fields Fwy"] = 50.0,
        ["Plaice Pl"] = 30.0,
        ["Chum St"] = 40.0,
        ["Chupacabra St"] = 30.0,
        ["Miriam Turner Overpass"] = 30.0,
        ["Autopia Pkwy"] = 35.0,
        ["Exceptionalists Way"] = 35.0,
        ["La Puerta Fwy"] = 65.0,
        ["New Empire Way"] = 30.0,
        ["Runway1"] = 70.0,
        ["Greenwich Pkwy"] = 35.0,
        ["Kortz Dr"] = 30.0,
        ["Banham Canyon Dr"] = 40.0,
        ["Buen Vino Rd"] = 40.0,
        ["Route 68"] = 55.0,
        ["Zancudo Grande Valley"] = 40.0,
        ["Zancudo Barranca"] = 40.0,
        ["Galileo Rd"] = 40.0,
        ["Mt Vinewood Dr"] = 40.0,
        ["Marlowe Dr"] = 40.0,
        ["Milton Rd"] = 35.0,
        ["Kimble Hill Dr"] = 35.0,
        ["Normandy Dr"] = 35.0,
        ["Hillcrest Ave"] = 35.0,
        ["Hillcrest Ridge Access Rd"] = 35.0,
        ["North Sheldon Ave"] = 35.0,
        ["Lake Vinewood Dr"] = 35.0,
        ["Lake Vinewood Est"] = 35.0,
        ["Baytree Canyon Rd"] = 40.0,
        ["North Conker Ave"] = 35.0,
        ["Wild Oats Dr"] = 35.0,
        ["Whispymound Dr"] = 35.0,
        ["Didion Dr"] = 35.0,
        ["Cox Way"] = 35.0,
        ["Picture Perfect Drive"] = 35.0,
        ["South Mo Milton Dr"] = 35.0,
        ["Cockingend Dr"] = 35.0,
        ["Mad Wayne Thunder Dr"] = 35.0,
        ["Hangman Ave"] = 35.0,
        ["Dunstable Ln"] = 35.0,
        ["Dunstable Dr"] = 35.0,
        ["Greenwich Way"] = 35.0,
        ["Greenwich Pl"] = 35.0,
        ["Hardy Way"] = 35.0,
        ["Richman St"] = 35.0,
        ["Ace Jones Dr"] = 35.0,
        ["Los Santos Freeway"] = 65.0,
        ["Senora Rd"] = 40.0,
        ["Nowhere Rd"] = 25.0,
        ["Smoke Tree Rd"] = 35.0,
        ["Cholla Rd"] = 35.0,
        ["Cat-Claw Ave"] = 35.0,
        ["Senora Way"] = 40.0,
        ["Palomino Fwy"] = 65.0,
        ["Shank St"] = 25.0,
        ["Macdonald St"] = 35.0,
        ["Route 68 Approach"] = 55.0,
        ["Vinewood Park Dr"] = 35.0,
        ["Vinewood Blvd"] = 40.0,
        ["Mirror Park Blvd"] = 35.0,
        ["Glory Way"] = 35.0,
        ["Bridge St"] = 35.0,
        ["West Mirror Drive"] = 35.0,
        ["Nikola Ave"] = 35.0,
        ["East Mirror Dr"] = 35.0,
        ["Nikola Pl"] = 25.0,
        ["Mirror Pl"] = 35.0,
        ["El Rancho Blvd"] = 40.0,
        ["Olympic Fwy"] = 65.0,
        ["Fudge Ln"] = 25.0,
        ["Amarillo Vista"] = 25.0,
        ["Labor Pl"] = 35.0,
        ["El Burro Blvd"] = 35.0,
        ["Sustancia Rd"] = 45.0,
        ["South Shambles St"] = 30.0,
        ["Hanger Way"] = 30.0,
        ["Orchardville Ave"] = 30.0,
        ["Popular St"] = 40.0,
        ["Buccaneer Way"] = 45.0,
        ["Abattoir Ave"] = 35.0,
        ["Voodoo Place"] = 30.0,
        ["Mutiny Rd"] = 35.0,
        ["South Arsenal St"] = 35.0,
        ["Forum Dr"] = 35.0,
        ["Morningwood Blvd"] = 35.0,
        ["Dorset Dr"] = 40.0,
        ["Caesars Place"] = 25.0,
        ["Spanish Ave"] = 30.0,
        ["Portola Dr"] = 30.0,
        ["Edwood Way"] = 25.0,
        ["San Vitus Blvd"] = 40.0,
        ["Eclipse Blvd"] = 35.0,
        ["Gentry Lane"] = 30.0,
        ["Las Lagunas Blvd"] = 40.0,
        ["Power St"] = 40.0,
        ["Mt Haan Rd"] = 40.0,
        ["Elgin Ave"] = 40.0,
        ["Hawick Ave"] = 35.0,
        ["Meteor St"] = 30.0,
        ["Alta Pl"] = 30.0,
        ["Occupation Ave"] = 35.0,
        ["Carcer Way"] = 40.0,
        ["Eastbourne Way"] = 30.0,
        ["Rockford Dr"] = 35.0,
        ["Abe Milton Pkwy"] = 35.0,
        ["Laguna Pl"] = 30.0,
        ["Sinners Passage"] = 30.0,
        ["Atlee St"] = 30.0,
        ["Sinner St"] = 30.0,
        ["Supply St"] = 30.0,
        ["Amarillo Way"] = 35.0,
        ["Tower Way"] = 35.0,
        ["Decker St"] = 35.0,
        ["Tackle St"] = 25.0,
        ["Galileo Park"] = 35.0,
        ["West Galileo Ave"] = 35.0,
        ["Tongva Dr"] = 40.0,
        ["Zancudo Rd"] = 35.0,
        ["Movie Star Way"] = 35.0,
        ["Heritage Way"] = 35.0,
        ["Perth St"] = 25.0,
        ["Chianski Passage"] = 30.0,
        ["Lolita Ave"] = 35.0,
        ["Meringue Ln"] = 35.0,
        ["Joshua Rd"] = 50.0,
        ["Low Power St"] = 35.0,
        ["Clinton Ave"] = 35.0,
        ["Fenwell Pl"] = 35.0,
        ["Utopia Gardens"] = 25.0,
        ["Cavalry Blvd"] = 35.0,
        ["South Boulevard Del Perro"] = 35.0,
        ["Americano Way"] = 25.0,
        ["Sam Austin Dr"] = 25.0,
        ["East Galileo Ave"] = 35.0,
    },
}




--░█▀▀█ ▒█░▒█ ▒█▀▀▄ ▀█▀ ▒█▀▀▀█ 　 ▒█▀▀▄ ▀█▀ ▒█▀▀▀█ ▒█▀▀█ ░█▀▀█ ▀▀█▀▀ ▒█▀▀█ ▒█░▒█ 
--▒█▄▄█ ▒█░▒█ ▒█░▒█ ▒█░ ▒█░░▒█ 　 ▒█░▒█ ▒█░ ░▀▀▀▄▄ ▒█▄▄█ ▒█▄▄█ ░▒█░░ ▒█░░░ ▒█▀▀█ 
--▒█░▒█ ░▀▄▄▀ ▒█▄▄▀ ▄█▄ ▒█▄▄▄█ 　 ▒█▄▄▀ ▄█▄ ▒█▄▄▄█ ▒█░░░ ▒█░▒█ ░▒█░░ ▒█▄▄█ ▒█░▒█





CrimeStrings = {
 
    ['1-87'] = {desc = " A Homicide ", Code = 3, Audio = {"CRIME_1_87_01.wav","CRIME_1_87_02.wav"}},
    ['1-48'] = {desc = " Suspect Fleeing Arrest ", Code = 3, Audio = {"CRIME_1_48_RESIST_ARREST_01.wav","CRIME_1_48_RESIST_ARREST_02.wav","CRIME_1_48_RESIST_ARREST_03.wav","CRIME_1_48_RESIST_ARREST_04.wav","CRIME_1_48_RESIST_ARREST_05.wav","CRIME_1_48_RESIST_ARREST_06.wav","CRIME_1_48_RESIST_ARREST_07.wav"}},
    ['2-07'] = {desc = " A Kidnapping ", Code = 3, Audio = {"CRIME_2_07_01.wav","CRIME_2_07_02.wav","CRIME_2_07_03.wav","CRIME_2_07_04.wav"}},
    ['2-11'] = {desc = " An Armed Robbery ", Code = 3, Audio = {"CRIME_2_11_01.wav","CRIME_2_11_02.wav","CRIME_2_11_03.wav"}},
    ['2-13'] = {desc = " Use of Explosives ", Code = 3, Audio = {"CRIME_2_13_01.wav","CRIME_2_13_02.wav"}},
    ['2-17'] = {desc = " Attempted Murder ", Code = 3, Audio = {"CRIME_2_17_01.wav","CRIME_2_17_02.wav"}},
    ['2-40'] = {desc = " A Homicide ", Code = 3, Audio = {"CRIME_2_40_01.wav","CRIME_2_40_02.wav"}},
    ['2-42'] = {desc = " A Battery ", Code = 2, Audio = {"CRIME_2_42_01.wav","CRIME_2_42_02.wav"}},
    ['2-45'] = {desc = " An Assault With A Deadly Weapon ", Code = 3, Audio = {"CRIME_2_45_01.wav","CRIME_2_45_02.wav","CRIME_2_45_03.wav","CRIME_2_45_04.wav","CRIME_2_45_05.wav"}},
    ['2-46'] = {desc = " A Shooting In A Dwelling ", Code = 1, Audio = {"CRIME_2_46_01.wav","CRIME_2_46_02.wav","CRIME_2_46_03.wav"}},
    ['3-11'] = {desc = " Indecent Exposure ", Code = 1, Audio = {"CRIME_3_11_01.wav","CRIME_3_11_02.wav","CRIME_3_11_03.wav"}},
    ['3-90'] = {desc = " Public Intoxication ", Code = 1, Audio = {"CRIME_3_90_01.wav","CRIME_3_90_02.wav","CRIME_3_90_03.wav"}},
    ['4-06'] = {desc = " Breaking And Entering ", Code = 1, Audio = {"CRIME_4_06_01.wav","CRIME_4_06_02.wav","CRIME_4_06_03.wav"}},
    ['4-15-G'] = {desc = " Gang Related Disturbance ", Code = 1, Audio = {"CRIME_4_15_GEORGE_01.wav","CRIME_4_15_GEORGE_02.wav","CRIME_4_15_GEORGE_03.wav"}},
    ['4-17'] = {desc = " Person With Weapon ", Code = 1, Audio = {"CRIME_4_17_01.wav","CRIME_4_17_02.wav","CRIME_4_17_03.wav"}},
    ['4-17-K'] = {desc = " Person With Knife ", Code = 1, Audio = {"CRIME_4_17_KING_01.wav","CRIME_4_17_KING_02.wav","CRIME_4_17_KING_03.wav","CRIME_4_17_KING_04.wav"}},
    ['4-19'] = {desc = " A Dead Body ", Code = 1, Audio = {"CRIME_4_19_01.wav","CRIME_4_19_02.wav","CRIME_4_19_03.wav","CRIME_4_19_04.wav","CRIME_4_19_05.wav"}},
    ['4-59'] = {desc = " A Burglary ", Code = 1, Audio = {"CRIME_4_59_01.wav","CRIME_4_59_02.wav"}},
    ['4-80'] = {desc = " A Hit And Run ", Code = 1, Audio = {"CRIME_4_80_01.wav","CRIME_4_80_02.wav","CRIME_4_80_03.wav","CRIME_4_80_04.wav"}},
    ['4-84'] = {desc = " A Petty Theft ", Code = 1, Audio = {"CRIME_4_84_01.wav","CRIME_4_84_02.wav","CRIME_4_84_03.wav"}},
    ['4-87'] = {desc = " A Grand Theft ", Code = 1, Audio = {"CRIME_4_87_01.wav","CRIME_4_87_02.wav","CRIME_4_87_03.wav"}},
    ['5-02'] = {desc = " A Driver Under The Influence ", Code = 1, Audio = {"CRIME_5_02_01.wav","CRIME_5_02_02.wav","CRIME_5_02_03.wav","CRIME_5_02_04.wav","CRIME_5_02_05.wav","CRIME_5_02_06.wav"}},
    ['5-03'] = {desc = " Auto Theft ", Code = 1, Audio = {"CRIME_5_03_01.wav","CRIME_5_03_02.wav","CRIME_5_03_03.wav","CRIME_5_03_04.wav"}}, -- redun
    ['5-04'] = {desc = " Tampering With A Vehicle ", Code = 1, Audio = {"CRIME_5_04_01.wav","CRIME_5_04_02.wav"}}, -- redun
    ['5-05'] = {desc = " Driver Out Of Control ", Code = 1, Audio = {"CRIME_5_05_01.wav","CRIME_5_05_02.wav"}},
    ['5-07'] = {desc = " Public Nuisance ", Code = 1, Audio = {"CRIME_5_07_01.wav","CRIME_5_07_02.wav"}},
    ['5-10'] = {desc = " Vehicle Racing / Speeding ", Code = 1, Audio = {"CRIME_5_10_01.wav","CRIME_5_10_02.wav","CRIME_5_10_03.wav"}},
    ['5-86'] = {desc = " Parking Violation ", Code = 1, Audio = {"CRIME_5_86_01.wav","CRIME_5_86_02.wav","CRIME_5_86_03.wav","CRIME_5_86_04.wav"}},
    ['5-94'] = {desc = " Malicious Mischief ", Code = 1, Audio = {"CRIME_5_94_01.wav","CRIME_5_94_02.wav","CRIME_5_94_03.wav"}},
    ['9-25'] = {desc = " Suspicous Person ", Code = 1, Audio = {"CRIME_9_25_01.wav","CRIME_9_25_02.wav"}},
    ['9-96-B'] = {desc = " An Explosion ", Code = 1, Audio = {"CRIME_9_96_BOY_01.wav","CRIME_9_96_BOY_02.wav"}},
    ['10-24'] = {desc = " Suspicous Person ", Code = 1, Audio = {"CRIME_10_24_01.wav","CRIME_10_24_02.wav","CRIME_10_24_03.wav","CRIME_10_24_04.wav"}},
    
    ['10-52'] = {desc = " An Ambulance Requested ", Code = 1, Audio = {"CRIME_AMBULANCE_REQUESTED_01.wav","CRIME_AMBULANCE_REQUESTED_02.wav","CRIME_AMBULANCE_REQUESTED_03.wav"}}, 
    ["10-71"]  = {desc = " Shots Fired ", Code = 1, Audio ={"CRIME_SHOTS_FIRED_1.wav","CRIME_SHOTS_FIRED_2.wav","CRIME_SHOTS_FIRED_3.wav","CRIME_SHOTS_FIRED_4.wav","CRIME_SHOTS_FIRED_5.wav"}},

    ['10-99'] = {desc = " Officer In Distress ", Code = 1, Audio = {"CRIME_10_99_01.wav","CRIME_10_99_02.wav","CRIME_10_99_03.wav","CRIME_10_99_04.wav"}}, 
    ['10-351'] = {desc = " Possesion Of Drugs For Sale ", Code = 1, Audio = {"CRIME_10_351_02.wav","CRIME_10_351_03.wav","CRIME_10_351_04.wav"}},
    ['10-851'] = {desc = " Stolen Vehicle ", Code = 1, Audio = {"CRIME_10_851_01.wav","CRIME_10_851_02.wav","CRIME_10_851_03.wav","CRIME_10_851_04.wav"}},
    ['11-351'] = {desc = " Possesion Of Drugs For Sale Incident ", Code = 1, Audio = {"CRIME_11_351_01.wav","CRIME_11_351_02.wav","CRIME_11_351_03.wav"}},
    ['11-357'] = {desc = " Possesion Of Drugs Incident ", Code = 1, Audio = {"CRIME_11_357_01.wav","CRIME_11_357_02.wav","CRIME_11_357_03.wav","CRIME_11_357_04.wav","CRIME_11_357_05.wav"}},
    ['11-71'] = {desc = " A Fire ", Code = 2, Audio = {"CRIME_11-71_FIRE_01.wav","CRIME_11-71_FIRE_02.wav","CRIME_11-71_FIRE_03.wav"}},
    ['11-78'] = {desc = " Aircraft accident ", Code = 1, Audio = {"CRIME_AIRPLANE_CRASH_01.wav","CRIME_AIRPLANE_CRASH_02.wav","CRIME_AIRPLANE_CRASH_03.wav"}},
    ['11-80'] = {desc = " Accident ", Code = 1, Audio = {"CRIME_ACCIDENT_01.wav"}},
    
    ['2-11-A'] = {desc = " An Armored Car Robbery ", Code = 1, Audio = {"CRIME_ARMORED_CAR_ROBBERY_01.wav","CRIME_ARMORED_CAR_ROBBERY_02.wav"}},
    ['2-11-B'] = {desc = " A Bank Robbery ", Code = 1, Audio = {"CRIME_BANK_ROBBERY_01.wav","CRIME_BANK_ROBBERY_02.wav","CRIME_BANK_ROBBERY_03.wav","CRIME_BANK_ROBBERY_04.wav","CRIME_BANK_ROBBERY_05.wav"}},
    ['2-41'] = {desc = " Assault On An Officer ", Code = 1, Audio = {"CRIME_ASSAULT_ON_AN_OFFICER_01.wav","CRIME_ASSAULT_ON_AN_OFFICER_02.wav"}},
    
    
    
    ['9-04-A'] = {desc = " A Vehicle On Fire ", Code = 2, Audio = {"CRIME_CAR_ON_FIRE_01.wav","CRIME_CAR_ON_FIRE_02.wav","CRIME_CAR_ON_FIRE_03.wav"}},
 
    
    ['10-78'] = {desc = " A Civilian In Need Of Assistance ", Code = 1, Audio = {"CRIME_CIVILIAN_NEEDING_ASSISTANCE_01.wav","CRIME_CIVILIAN_NEEDING_ASSISTANCE_02.wav"}},
    
    
    ['10-31'] = {desc = " A Crime In Progress ", Code = 1, Audio = {"CRIME_CRIMINAL_ACTIVITY_01.wav","CRIME_CRIMINAL_ACTIVITY_02.wav","CRIME_CRIMINAL_ACTIVITY_03.wav","CRIME_CRIMINAL_ACTIVITY_04.wav","CRIME_CRIMINAL_ACTIVITY_05.wav"}},

    ['10-38'] = {desc = " A Dangerous Driver ", Code = 1, Audio = {"CRIME_DANGEROUS_DRIVING_01.wav","CRIME_DANGEROUS_DRIVING_02.wav","CRIME_CRIMINAL_ACTIVITY_03.wav"}},


    

    ['1-87'] = {desc = " A Homicide ", Code = 1, Audio = {"CRIME_1_87_01.wav","CRIME_1_87_02.wav"}},
}




--▀▀█▀▀ ▒█▀▀▀ ▀▄▒▄▀ ▀▀█▀▀ 　 ▒█▀▀▄ ▀█▀ ▒█▀▀▀█ ▒█▀▀█ ░█▀▀█ ▀▀█▀▀ ▒█▀▀█ ▒█░▒█ 
--░▒█░░ ▒█▀▀▀ ░▒█░░ ░▒█░░ 　 ▒█░▒█ ▒█░ ░▀▀▀▄▄ ▒█▄▄█ ▒█▄▄█ ░▒█░░ ▒█░░░ ▒█▀▀█ 
--░▒█░░ ▒█▄▄▄ ▄▀▒▀▄ ░▒█░░ 　 ▒█▄▄▀ ▄█▄ ▒█▄▄▄█ ▒█░░░ ▒█░▒█ ░▒█░░ ▒█▄▄█ ▒█░▒█

firedWeapons = { -- This is used for the text descriptions for weapons
    {weaponText = "pistol" , weaponname =  'WEAPON_PISTOL'},
    {weaponText = "pistol" , weaponname =  'WEAPON_COMBATPISTOL'},
    {weaponText = "pistol" , weaponname =  'WEAPON_SNSPISTOL'},
    {weaponText = "pistol" , weaponname =  'WEAPON_HEAVYPISTOL'},
    {weaponText = "pistol" , weaponname =  'WEAPON_VINTAGEPISTOL'},
    {weaponText = "pistol" , weaponname =  'WEAPON_PISTOL50'},
    {weaponText = "pistol" , weaponname =  'WEAPON_DOUBLEACTION'},
    {weaponText = "pistol" , weaponname =  'WEAPON_REVOLVER'},
    {weaponText = "pistol" , weaponname =  'WEAPON_FLAREGUN'},
    {weaponText = "pistol" , weaponname =  'WEAPON_SPECIALCARBINE_MK2'},
    {weaponText = "pistol" , weaponname =  'WEAPON_COMPACTRIFLE'},
    {weaponText = "pistol" , weaponname =  'WEAPON_CERAMICPISTOL'},
    {weaponText = "pistol" , weaponname =  'WEAPON_NAVYREVOLVER'},
    {weaponText = "pistol" , weaponname =  'WEAPON_GADGETPISTOL'},

    {weaponText = "automatic pistol" , weaponname =  'WEAPON_APPISTOL'},
  

	{weaponText = "shotgun" , weaponname = 'WEAPON_PUMPSHOTGUN_MK2'},
    {weaponText = "shotgun" , weaponname = 'WEAPON_PUMPSHOTGUN'},
    {weaponText = "shotgun" , weaponname = 'WEAPON_SAWNOFFSHOTGUN'},
    {weaponText = "shotgun" , weaponname = 'WEAPON_ASSAULTSHOTGUN'},
    {weaponText = "shotgun" , weaponname = 'WEAPON_BULLPUPSHOTGUN'},
    {weaponText = "shotgun" , weaponname = 'WEAPON_HEAVYSHOTGUN'},
    {weaponText = "shotgun" , weaponname = 'WEAPON_DBSHOTGUN'},
    {weaponText = "shotgun" , weaponname = 'WEAPON_AUTOSHOTGUN'},
    {weaponText = "shotgun" , weaponname = 'WEAPON_COMBATSHOTGUN'},
    

	--Smg

	{weaponText = 'smg' , weaponname = 'WEAPON_SMG_MK2'},
    {weaponText = 'smg' , weaponname = 'WEAPON_MICROSMG'},
    {weaponText = 'smg' , weaponname = 'WEAPON_SMG_MK2'},
    {weaponText = 'smg' , weaponname = 'WEAPON_ASSAULTSMG'},
    {weaponText = 'smg' , weaponname = 'WEAPON_MACHINEPISTOL'},
    {weaponText = 'smg' , weaponname = 'WEAPON_MINISMG'},
    {weaponText = 'smg' , weaponname = 'WEAPON_COMPACTRIFLE'},
    {weaponText = 'smg' , weaponname = 'WEAPON_COMBATPDW'},
    {weaponText = 'smg' , weaponname = 'WEAPON_GUSENBERG'},
    {weaponText = 'smg' , weaponname = 'WEAPON_SMG'},
    
	--Assualt Rifle
	{weaponText = 'automatic rifle' , weaponname = 'WEAPON_COMBATMG_MK2'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_SPECIALCARBINE'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_ADVANCEDRIFLE'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_SPECIALCARBINE_MK2'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_CARBINERIFLE_MK2'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_CARBINERIFLE'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_ASSAULTRIFLE'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_ASSAULTRIFLE_MK2'},

	--Heavy Weapons
	{weaponText = 'machinegun' , weaponname = 'WEAPON_MG'},
    {weaponText = 'machinegun' , weaponname = 'WEAPON_COMBATMG'},
    {weaponText = 'sniper rifle' , weaponname = 'WEAPON_SNIPERRIFLE'},
    {weaponText = 'sniper rifle' , weaponname = 'WEAPON_HEAVYSNIPER'},

    {weaponText = 'musket' , weaponname = 'WEAPON_MUSKET'},

    {weaponText = 'alien rifle' , weaponname = 'WEAPON_RAYCARBINE'},



    --░░░░░░░░░░░░███████╗██████╗░██╗████████╗░░░░░░░░░░░░
    --░░░░░░░░░░░░██╔════╝██╔══██╗██║╚══██╔══╝░░░░░░░░░░░░
    --█████╗█████╗█████╗░░██║░░██║██║░░░██║░░░█████╗█████╗
    --╚════╝╚════╝██╔══╝░░██║░░██║██║░░░██║░░░╚════╝╚════╝
    --░░░░░░░░░░░░███████╗██████╔╝██║░░░██║░░░░░░░░░░░░░░░
    --░░░░░░░░░░░░╚══════╝╚═════╝░╚═╝░░░╚═╝░░░░░░░░░░░░░░░
    --EDIT: Add YOUR Addon Weapons here 

--[[-------------------- ADDON EXAMPLE  ------------------------------------------

    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_CAR15'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_VZ58'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_CLASSICRIFLE'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_M16A2'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_NAVYCARBINE'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_PRECISIONCARBINE'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_STAMPEDRIFLE'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_TACTICALCARBINE'},
    {weaponText = 'automatic rifle' , weaponname = 'WEAPON_PROTORIFLE'},

    {weaponText = 'rifle' , weaponname = 'WEAPON_RUSSIANSNIPER'},

    {weaponText = 'smg' , weaponname = 'WEAPON_MP5'},
    {weaponText = "pistol" , weaponname =  'WEAPON_ENDURANCE'},
    {weaponText = "pistol" , weaponname =  'WEAPON_DP9'},
    {weaponText = "pistol" , weaponname =  'WEAPON_GLOCK45'},
    {weaponText = "automatic pistol" , weaponname =  'WEAPON_GLOCK18'},
    {weaponText = "flamethrower" , weaponname =  'WEAPON_FLAMETHROWER'}, ]]
}
HairColors = {
    {color = 0 , label = "black" },
    {color = 1 , label = "black" },
    {color = 2 , label = "brown"  },
    {color = 3 , label = "brown"  },
    {color = 4 , label = "brown"  },
    {color = 5 , label = "brown"  },
    {color = 6 , label = "brown"  },
    {color = 7 , label = "blonde"  },
    {color = 8 , label = "blonde"  },
    {color = 9 , label = "blonde"  },
    {color = 10 , label = "blonde"  },
    {color = 11 , label = "blonde"  },
    {color = 12 , label = "blonde"  },
    {color = 13 , label = "blonde"  },
    {color = 14 , label = "blonde"  },
    {color = 15 , label = "blonde"  },
    {color = 16 , label = "blonde"  },
    {color = 17 , label = "red"  },
    {color = 18 , label = "red"  },
    {color = 19 , label = "red"  },
    {color = 20 , label = "red"  },
    {color = 21 , label = "red"  },
    {color = 22 , label = "red"  },
    {color = 23 , label = "orange"  },
    {color = 24 , label = "orange"  },
    {color = 25 , label = "orange"  },
    {color = 26 , label = "grey"  },
    {color = 27 , label = "grey"  },
    {color = 28 , label = "white"  },
    {color = 29 , label = "white"  },
    {color = 30 , label = "purple"  },
    {color = 31 , label = "purple"  },
    {color = 32 , label = "purple"  },
    {color = 33 , label = "pink"  },
    {color = 34 , label = "pink"  },
    {color = 35 , label = "pink"  },
    {color = 36 , label = "blue"  },
    {color = 37 , label = "blue"  },
    {color = 38 , label = "blue"  },
    {color = 39 , label = "green"  },
    {color = 40 , label = "green"  },
    {color = 41 , label = "green"  },
    {color = 42 , label = "green"  },
    {color = 43 , label = "green"  },
    {color = 44 , label = "green"  },
    {color = 45 , label = "gold"  },
    {color = 46 , label = "gold"  },
    {color = 47 , label = "gold"  },
    {color = 48 , label = "orange"  },
    {color = 49 , label = "orange"  },
    {color = 50 , label = "orange"  },
    {color = 51 , label = "orange"  },
    {color = 52 , label = "red"  },
    {color = 53 , label = "red"  },
    {color = 54 , label = "red"  },
    {color = 55 , label = "brown"  },
    {color = 56 , label = "brown"  },
    {color = 57 , label = "brown"  },
    {color = 58 , label = "brown"  },
    {color = 59 , label = "brown"  },
    {color = 60 , label = "brown"  },
    {color = 61 , label = "black"  },
    {color = 62 , label = "grey"  },
    {color = 63 , label = "blonde"  },
}
classTexts ={
    {number = 0 , text = "Compact car" },
    {number = 1 , text = "Sedan" },
    {number = 2 , text = "SUV" },
    {number = 3 , text = "Coupe" },
    {number = 4 , text = "Muscle car" },
    {number = 5 , text = "Sports Classic Car" },
    {number = 6 , text = "Sports Car" },
    {number = 7 , text = "Super Car" },
    {number = 8 , text = "Motorcycle" },
    {number = 9 , text = "Off-road  Vehicle" },
    {number = 10 , text = "Industrial Vehicle" },
    {number = 11 , text = "Utility Vehicle" },
    {number = 12 , text = "Van" },
    {number = 13 , text = "Bicycle" },
    {number = 14 , text = "Boat" },
    {number = 15 , text = "Helicopter" },
    {number = 16 , text = "Plane" },
    {number = 17 , text = "Service Vehicle" },
    {number = 18 , text = "Emergency Vehicle" },
    {number = 19 , text = "Military Vehicle" },
    {number = 20 , text = "Commercial Vehicle" },
    {number = 21 , text = "Train"},
}
vehiclecolorTexts ={
    { int =0, colortext = "Metallic Black"},
    { int = 1, colortext = "Metallic Graphite Black"},
    { int = 2, colortext = "Metallic Black Steal"},
    { int = 3, colortext = "Metallic Dark Silver"},
    { int = 4, colortext = "Metallic Silver"},
    { int = 5, colortext = "Metallic Blue Silver"},
    { int = 6, colortext = "Metallic Steel Gray"},
    { int = 7, colortext = "Metallic Shadow Silver"},
    { int = 8, colortext = "Metallic Stone Silver"},
    { int = 9, colortext = "Metallic Midnight Silver"},
    { int = 10, colortext = "Metallic Gun Metal"},
    { int = 11, colortext = "Metallic Anthracite Grey"},
    { int = 12, colortext = "Matte Black"},
    { int = 13, colortext = "Matte Gray"},
    { int = 14, colortext = "Matte Light Grey"},
    { int = 15, colortext = "Util Black"},
    { int = 16, colortext = "Util Black Poly"},
    { int = 17, colortext = "Util Dark silver"},
    { int = 18, colortext = "Util Silver"},
    { int = 19, colortext = "Util Gun Metal"},
    { int = 20, colortext = "Util Shadow Silver"},
    { int = 21, colortext = "Worn Black"},
    { int = 22, colortext = "Worn Graphite"},
    { int = 23, colortext = "Worn Silver Grey"},
    { int = 24, colortext = "Worn Silver"},
    { int = 25, colortext = "Worn Blue Silver"},
    { int = 26, colortext = "Worn Shadow Silver"},
    { int = 27, colortext = "Metallic Red"},
    { int = 28, colortext = "Metallic Torino Red"},
    { int = 29, colortext = "Metallic Formula Red"},
    { int = 30, colortext = "Metallic Blaze Red"},
    { int = 31, colortext = "Metallic Graceful Red"},
    { int = 32, colortext = "Metallic Garnet Red"},
    { int = 33, colortext = "Metallic Desert Red"},
    { int = 34, colortext = "Metallic Cabernet Red"},
    { int = 35, colortext = "Metallic Candy Red"},
    { int = 36, colortext = "Metallic Sunrise Orange"},
    { int = 37, colortext = "Metallic Classic Gold"},
    { int = 38, colortext = "Metallic Orange"},
    { int = 39, colortext = "Matte Red"},
    { int = 40, colortext = "Matte Dark Red"},
    { int = 41, colortext = "Matte Orange"},
    { int = 42, colortext = "Matte Yellow"},
    { int = 43, colortext = "Util Red"},
    { int = 44, colortext = "Util Bright Red"},
    { int = 45, colortext = "Util Garnet Red"},
    { int = 46, colortext = "Worn Red"},
    { int = 47, colortext = "Worn Golden Red"},
    { int = 48, colortext = "Worn Dark Red"},
    { int = 49, colortext = "Metallic Dark Green"},
    { int = 50, colortext = "Metallic Racing Green"},
    { int = 51, colortext = "Metallic Sea Green"},
    { int = 52, colortext = "Metallic Olive Green"},
    { int = 53, colortext = "Metallic Green"},
    { int = 54, colortext = "Metallic Gasoline Blue Green"},
    { int = 55, colortext = "Matte Lime Green"},
    { int = 56, colortext = "Util Dark Green"},
    { int = 57, colortext = "Util Green"},
    { int = 58, colortext = "Worn Dark Green"},
    { int = 59, colortext = "Worn Green"},
    { int = 60, colortext = "Worn Sea Wash"},
    { int = 61, colortext = "Metallic Midnight Blue"},
    { int = 62, colortext = "Metallic Dark Blue"},
    { int = 63, colortext = "Metallic Saxony Blue"},
    { int = 64, colortext = "Metallic Blue"},
    { int = 65, colortext = "Metallic Mariner Blue"},
    { int = 66, colortext = "Metallic Harbor Blue"},
    { int = 67, colortext = "Metallic Diamond Blue"},
    { int = 68, colortext = "Metallic Surf Blue"},
    { int = 69, colortext = "Metallic Nautical Blue"},
    { int = 70, colortext = "Metallic Bright Blue"},
    { int = 71, colortext = "Metallic Purple Blue"},
    { int = 72, colortext = "Metallic Spinnaker Blue"},
    { int = 73, colortext = "Metallic Ultra Blue"},
    { int = 74, colortext = "Metallic Bright Blue"},
    { int = 75, colortext = "Util Dark Blue"},
    { int = 76, colortext = "Util Midnight Blue"},
    { int = 77, colortext = "Util Blue"},
    { int = 78, colortext = "Util Sea Foam Blue"},
    { int = 79, colortext = "Util Lightning blue"},
    { int = 80, colortext = "Util Maui Blue Poly"},
    { int = 81, colortext = "Util Bright Blue"},
    { int = 82, colortext = "Matte Dark Blue"},
    { int = 83, colortext = "Matte Blue"},
    { int = 84, colortext = "Matte Midnight Blue"},
    { int = 85, colortext = "Worn Dark blue"},
    { int = 86, colortext = "Worn Blue"},
    { int = 87, colortext = "Worn Light blue"},
    { int = 88, colortext = "Metallic Taxi Yellow"},
    { int = 89, colortext = "Metallic Race Yellow"},
    { int = 90, colortext = "Metallic Bronze"},
    { int = 91, colortext = "Metallic Yellow Bird"},
    { int = 92, colortext = "Metallic Lime"},
    { int = 93, colortext = "Metallic Champagne"},
    { int = 94, colortext = "Metallic Pueblo Beige"},
    { int = 95, colortext = "Metallic Dark Ivory"},
    { int = 96, colortext = "Metallic Choco Brown"},
    { int = 97, colortext = "Metallic Golden Brown"},
    { int = 98, colortext = "Metallic Light Brown"},
    { int = 99, colortext = "Metallic Straw Beige"},
    { int = 100, colortext = "Metallic Moss Brown"},
    { int = 101, colortext = "Metallic Biston Brown"},
    { int = 102, colortext = "Metallic Beechwood"},
    { int = 103, colortext = "Metallic Dark Beechwood"},
    { int = 104, colortext = "Metallic Choco Orange"},
    { int = 105, colortext = "Metallic Beach Sand"},
    { int = 106, colortext = "Metallic Sun Bleeched Sand"},
    { int = 107, colortext = "Metallic Cream"},
    { int = 108, colortext = "Util Brown"},
    { int = 109, colortext = "Util Medium Brown"},
    { int = 110, colortext = "Util Light Brown"},
    { int = 111, colortext = "Metallic White"},
    { int = 112, colortext = "Metallic Frost White"},
    { int = 113, colortext = "Worn Honey Beige"},
    { int = 114, colortext = "Worn Brown"},
    { int = 115, colortext = "Worn Dark Brown"},
    { int = 116, colortext = "Worn straw beige"},
    { int = 117, colortext = "Brushed Steel"},
    { int = 118, colortext = "Brushed Black steel"},
    { int = 119, colortext = "Brushed Aluminium"},
    { int = 120, colortext = "Chrome"},
    { int = 121, colortext = "Worn Off White"},
    { int = 122, colortext = "Util Off White"},
    { int = 123, colortext = "Worn Orange"},
    { int = 124, colortext = "Worn Light Orange"},
    { int = 125, colortext = "Metallic Securicor Green"},
    { int = 126, colortext = "Worn Taxi Yellow"},
    { int = 127, colortext = "police car blue"},
    { int = 128, colortext = "Matte Green"},
    { int = 129, colortext = "Matte Brown"},
    { int = 130, colortext = "Worn Orange"},
    { int = 131, colortext = "Matte White"},
    { int = 132, colortext = "Worn White"},
    { int = 133, colortext = "Worn Olive Army Green"},
    { int = 134, colortext = "Pure White"},
    { int = 135, colortext = "Hot Pink"},
    { int = 136, colortext = "Salmon pink"},
    { int = 137, colortext = "Metallic Vermillion Pink"},
    { int = 138, colortext = "Orange"},
    { int = 139, colortext = "Green"},
    { int = 140, colortext = "Blue"},
    { int = 141, colortext = "Mettalic Black Blue"},
    { int = 142, colortext = "Metallic Black Purple"},
    { int = 143, colortext = "Metallic Black Red"},
    { int = 144, colortext = "hunter green"},
    { int = 145, colortext = "Metallic Purple"},
    { int = 146, colortext = "Metaillic V Dark Blue"},
    { int = 147, colortext = "MODSHOP BLACK1"},
    { int = 148, colortext = "Matte Purple"},
    { int = 149, colortext = "Matte Dark Purple"},
    { int = 150, colortext = "Metallic Lava Red"},
    { int = 151, colortext = "Matte Forest Green"},
    { int = 152, colortext = "Matte Olive Drab"},
    { int = 153, colortext = "Matte Desert Brown"},
    { int = 154, colortext = "Matte Desert Tan"},
    { int = 155, colortext = "Matte Foilage Green"},
    { int = 156, colortext = "DEFAULT ALLOY COLOR"},
    { int = 157, colortext = "Epsilon Blue"},
    { int = 158, colortext = "Pure Gold"},
    { int = 159, colortext = "Brushed Gold "}
}

