fx_version 'adamant'
games { 'gta5' }

author 'NVE Team'
description 'nopixel 4.0 - Lights'
version '1.0.0'

this_is_a_map 'yes'

lua54 'yes'

data_file 'DLC_ITYP_REQUEST' 'stream/animation_stuff1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/arena_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bahama_drink.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bahama_logo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bahama_neons.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bahama_windows_neon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/bhgas_signs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/carwash_arrowsign_bulbs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/carwash_sign_handson.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/carwash_slopes.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/city_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/city_lights.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/city_props.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/dashhound_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/dionysia_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/hood_sign.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/hookies_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ktgas_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/laserlight.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/ltdgrove_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/mall_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/milgas_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/nopixel_anims.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/nve_volumecaster.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/rongas_highway_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/rongas_hood_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/sstorage_meta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/truckgas_neon.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vinewood_lights.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vu_sign_bulbs.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vu_sign_girls.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vu_sign_open.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/vu_sign_unicorn.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/watertest.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/wind_ads.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/xerogas_ref_proxies.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/xerogas_sign_neon.ytyp'
dependency '/assetpacks'