function GetLocale(text)
    local locales = Locales[Config.Locale]
    if locales and locales[text] then
        return locales[text]
    end
    return text
end

function GetVehicleLabel(model)
    local vehicleLabel = GetDisplayNameFromVehicleModel(model):lower()

    if not vehicleLabel or vehicleLabel == "null" or vehicleLabel == "carnotfound" then
        vehicleLabel = "Unknown"
    else
        local text = GetLabelText(vehicleLabel)
        if text and text:lower() ~= "null" then
            vehicleLabel = text
        end
    end
    return vehicleLabel
end

local vehicleColors = {
    [0] = { label = "Metallic Black", hex = "#0d1116" },
    [1] = { label = "Metallic Graphite Black", hex = "#1c1d21" },
    [2] = { label = "Metallic Black Steal", hex = "#32383d" },
    [3] = { label = "Metallic Dark Silver", hex = "#454b4f" },
    [4] = { label = "Metallic Silver", hex = "#999da0" },
    [5] = { label = "Metallic Blue Silver", hex = "#c2c4c6" },
    [6] = { label = "Metallic Steel Gray", hex = "#979a97" },
    [7] = { label = "Metallic Shadow Silver", hex = "#637380" },
    [8] = { label = "Metallic Stone Silver", hex = "#63625c" },
    [9] = { label = "Metallic Midnight Silver", hex = "#3c3f47" },
    [10] = { label = "Metallic Gun Metal", hex = "#444e54" },
    [11] = { label = "Metallic Anthracite Grey", hex = "#1d2129" },
    [12] = { label = "Matte Black", hex = "#13181f" },
    [13] = { label = "Matte Gray", hex = "#26282a" },
    [14] = { label = "Matte Light Grey", hex = "#515554" },
    [15] = { label = "Util Black", hex = "#151921" },
    [16] = { label = "Util Black Poly", hex = "#1e2429" },
    [17] = { label = "Util Dark silver", hex = "#333a3c" },
    [18] = { label = "Util Silver", hex = "#8c9095" },
    [19] = { label = "Util Gun Metal", hex = "#39434d" },
    [20] = { label = "Util Shadow Silver", hex = "#506272" },
    [21] = { label = "Worn Black", hex = "#1e232f" },
    [22] = { label = "Worn Graphite", hex = "#363a3f" },
    [23] = { label = "Worn Silver Grey", hex = "#a0a199" },
    [24] = { label = "Worn Silver", hex = "#d3d3d3" },
    [25] = { label = "Worn Blue Silver", hex = "#b7bfca" },
    [26] = { label = "Worn Shadow Silver", hex = "#778794" },
    [27] = { label = "Metallic Red", hex = "#c00e1a" },
    [28] = { label = "Metallic Torino Red", hex = "#da1918" },
    [29] = { label = "Metallic Formula Red", hex = "#b6111b" },
    [30] = { label = "Metallic Blaze Red", hex = "#a51e23" },
    [31] = { label = "Metallic Graceful Red", hex = "#7b1a22" },
    [32] = { label = "Metallic Garnet Red", hex = "#8e1b1f" },
    [33] = { label = "Metallic Desert Red", hex = "#6f1818" },
    [34] = { label = "Metallic Cabernet Red", hex = "#49111d" },
    [35] = { label = "Metallic Candy Red", hex = "#b60f25" },
    [36] = { label = "Metallic Sunrise Orange", hex = "#d44a17" },
    [37] = { label = "Metallic Classic Gold", hex = "#c2944f" },
    [38] = { label = "Metallic Orange", hex = "#f78616" },
    [39] = { label = "Matte Red", hex = "#cf1f21" },
    [40] = { label = "Matte Dark Red", hex = "#732021" },
    [41] = { label = "Matte Orange", hex = "#f27d20" },
    [42] = { label = "Matte Yellow", hex = "#ffc91f" },
    [43] = { label = "Util Red", hex = "#9c1016" },
    [44] = { label = "Util Bright Red", hex = "#de0f18" },
    [45] = { label = "Util Garnet Red", hex = "#8f1e17" },
    [46] = { label = "Worn Red", hex = "#a94744" },
    [47] = { label = "Worn Golden Red", hex = "#b16c51" },
    [48] = { label = "Worn Dark Red", hex = "#371c25" },
    [49] = { label = "Metallic Dark Green", hex = "#132428" },
    [50] = { label = "Metallic Racing Green", hex = "#122e2b" },
    [51] = { label = "Metallic Sea Green", hex = "#12383c" },
    [52] = { label = "Metallic Olive Green", hex = "#31423f" },
    [53] = { label = "Metallic Green", hex = "#155c2d" },
    [54] = { label = "Metallic Gasoline Blue Green", hex = "#1b6770" },
    [55] = { label = "Matte Lime Green", hex = "#66b81f" },
    [56] = { label = "Util Dark Green", hex = "#22383e" },
    [57] = { label = "Util Green", hex = "#1d5a3f" },
    [58] = { label = "Worn Dark Green", hex = "#2d423f" },
    [59] = { label = "Worn Green", hex = "#45594b" },
    [60] = { label = "Worn Sea Wash", hex = "#65867f" },
    [61] = { label = "Metallic Midnight Blue", hex = "#222e46" },
    [62] = { label = "Metallic Dark Blue", hex = "#233155" },
    [63] = { label = "Metallic Saxony Blue", hex = "#304c7e" },
    [64] = { label = "Metallic Blue", hex = "#47578f" },
    [65] = { label = "Metallic Mariner Blue", hex = "#637ba7" },
    [66] = { label = "Metallic Harbor Blue", hex = "#394762" },
    [67] = { label = "Metallic Diamond Blue", hex = "#d6e7f1" },
    [68] = { label = "Metallic Surf Blue", hex = "#76afbe" },
    [69] = { label = "Metallic Nautical Blue", hex = "#345e72" },
    [70] = { label = "Metallic Bright Blue", hex = "#0b9cf1" },
    [71] = { label = "Metallic Purple Blue", hex = "#2f2d52" },
    [72] = { label = "Metallic Spinnaker Blue", hex = "#282c4d" },
    [73] = { label = "Metallic Ultra Blue", hex = "#2354a1" },
    [74] = { label = "Metallic Bright Blue", hex = "#6ea3c6" },
    [75] = { label = "Util Dark Blue", hex = "#112552" },
    [76] = { label = "Util Midnight Blue", hex = "#1b203e" },
    [77] = { label = "Util Blue", hex = "#275190" },
    [78] = { label = "Util Sea Foam Blue", hex = "#608592" },
    [79] = { label = "Util Lightning blue", hex = "#2446a8" },
    [80] = { label = "Util Maui Blue Poly", hex = "#4271e1" },
    [81] = { label = "Util Bright Blue", hex = "#3b39e0" },
    [82] = { label = "Matte Dark Blue", hex = "#1f2852" },
    [83] = { label = "Matte Blue", hex = "#253aa7" },
    [84] = { label = "Matte Midnight Blue", hex = "#1c3551" },
    [85] = { label = "Worn Dark blue", hex = "#4c5f81" },
    [86] = { label = "Worn Blue", hex = "#58688e" },
    [87] = { label = "Worn Light blue", hex = "#74b5d8" },
    [88] = { label = "Metallic Taxi Yellow", hex = "#ffcf20" },
    [89] = { label = "Metallic Race Yellow", hex = "#fbe212" },
    [90] = { label = "Metallic Bronze", hex = "#916532" },
    [91] = { label = "Metallic Yellow Bird", hex = "#e0e13d" },
    [92] = { label = "Metallic Lime", hex = "#98d223" },
    [93] = { label = "Metallic Champagne", hex = "#9b8c78" },
    [94] = { label = "Metallic Pueblo Beige", hex = "#503218" },
    [95] = { label = "Metallic Dark Ivory", hex = "#473f2b" },
    [96] = { label = "Metallic Choco Brown", hex = "#221b19" },
    [97] = { label = "Metallic Golden Brown", hex = "#653f23" },
    [98] = { label = "Metallic Light Brown", hex = "#775c3e" },
    [99] = { label = "Metallic Straw Beige", hex = "#ac9975" },
    [100] = { label = "Metallic Moss Brown", hex = "#6c6b4b" },
    [101] = { label = "Metallic Biston Brown", hex = "#402e2b" },
    [102] = { label = "Metallic Beechwood", hex = "#a4965f" },
    [103] = { label = "Metallic Dark Beechwood", hex = "#46231a" },
    [104] = { label = "Metallic Choco Orange", hex = "#752b19" },
    [105] = { label = "Metallic Beach Sand", hex = "#bfae7b" },
    [106] = { label = "Metallic Sun Bleeched Sand", hex = "#dfd5b2" },
    [107] = { label = "Metallic Cream", hex = "#f7edd5" },
    [108] = { label = "Util Brown", hex = "#3a2a1b" },
    [109] = { label = "Util Medium Brown", hex = "#785f33" },
    [110] = { label = "Util Light Brown", hex = "#b5a079" },
    [111] = { label = "Metallic White", hex = "#fffff6" },
    [112] = { label = "Metallic Frost White", hex = "#eaeaea" },
    [113] = { label = "Worn Honey Beige", hex = "#b0ab94" },
    [114] = { label = "Worn Brown", hex = "#453831" },
    [115] = { label = "Worn Dark Brown", hex = "#2a282b" },
    [116] = { label = "Worn straw beige", hex = "#726c57" },
    [117] = { label = "Brushed Steel", hex = "#6a747c" },
    [118] = { label = "Brushed Black steel", hex = "#354158" },
    [119] = { label = "Brushed Aluminium", hex = "#9ba0a8" },
    [120] = { label = "Chrome", hex = "#5870a1" },
    [121] = { label = "Worn Off White", hex = "#eae6de" },
    [122] = { label = "Util Off White", hex = "#dfddd0" },
    [123] = { label = "Worn Orange", hex = "#f2ad2e" },
    [124] = { label = "Worn Light Orange", hex = "#f9a458" },
    [125] = { label = "Metallic Securicor Green", hex = "#83c566" },
    [126] = { label = "Worn Taxi Yellow", hex = "#f1cc40" },
    [127] = { label = "police car blue", hex = "#4cc3da" },
    [128] = { label = "Matte Green", hex = "#4e6443" },
    [129] = { label = "Matte Brown", hex = "#bcac8f" },
    [130] = { label = "Worn Orange", hex = "#f8b658" },
    [131] = { label = "Matte White", hex = "#fcf9f1" },
    [132] = { label = "Worn White", hex = "#fffffb" },
    [133] = { label = "Worn Olive Army Green", hex = "#81844c" },
    [134] = { label = "Pure White", hex = "#ffffff" },
    [135] = { label = "Hot Pink", hex = "#f21f99" },
    [136] = { label = "Salmon pink", hex = "#fdd6cd" },
    [137] = { label = "Metallic Vermillion Pink", hex = "#df5891" },
    [138] = { label = "Orange", hex = "#f6ae20" },
    [139] = { label = "Green", hex = "#b0ee6e" },
    [140] = { label = "Blue", hex = "#08e9fa" },
    [141] = { label = "Mettalic Black Blue", hex = "#0a0c17" },
    [142] = { label = "Metallic Black Purple", hex = "#0c0d18" },
    [143] = { label = "Metallic Black Red", hex = "#0e0d14" },
    [144] = { label = "hunter green", hex = "#9f9e8a" },
    [145] = { label = "Metallic Purple", hex = "#621276" },
    [146] = { label = "Metaillic V Dark Blue", hex = "#0b1421" },
    [147] = { label = "MODSHOP BLACK1", hex = "#11141a" },
    [148] = { label = "Matte Purple", hex = "#6b1f7b" },
    [149] = { label = "Matte Dark Purple", hex = "#1e1d22" },
    [150] = { label = "Metallic Lava Red", hex = "#bc1917" },
    [151] = { label = "Matte Forest Green", hex = "#2d362a" },
    [152] = { label = "Matte Olive Drab", hex = "#696748" },
    [153] = { label = "Matte Desert Brown", hex = "#7a6c55" },
    [154] = { label = "Matte Desert Tan", hex = "#c3b492" },
    [155] = { label = "Matte Foilage Green", hex = "#5a6352" },
    [156] = { label = "DEFAULT ALLOY COLOR", hex = "#81827f" },
    [157] = { label = "Epsilon Blue", hex = "#afd6e4" },
    [158] = { label = "Pure Gold", hex = "#7a6440" },
    [159] = { label = "Brushed Gold", hex = "#7f6a48" },
}

function GetVehicleColor(color)
    return vehicleColors[color] or {
        label = "Unknown Color",
        hex = "#ffffff"
    }
end